export enum Estado {
    SOLICITADO = "SOLICITADO",
    PENDIENTE = "PENDIENTE",
    EN_PREPARACION = "EN_PREPARACION",
    TERMINADO = "TERMINADO",
    EN_CAMINO = "EN_CAMINO",
    ENTREGADO = "ENTREGADO",
    CANCELADO = "CANCELADO"
}