export enum Estado {
    PENDIENTE_FACTURACION = "PENDIENTE_FACTURACION",
    SOLICITADO = "SOLICITADO",
    EN_PREPARACION = "EN_PREPARACION",
    TERMINADO = "TERMINADO",
    EN_CAMINO = "EN_CAMINO",
    ENTREGADO = "ENTREGADO",
    CANCELADO = "CANCELADO"
}